os: linux
language: node_js
node_js:
  - "16"
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
before_script:
  - npm install -g @angular/cli
  - npm install -g codecov
script:
  - npm run lint:lib
  - npm run test-ci
  - codecov
  - npm run build:lib
after_script:
      - cat ./coverage/gallery/lcov.info | coveralls
before_deploy:
  - npm run copy:readme
  - npm run copy:changelog
  - npm run copy:license
  - cd dist/gallery
deploy:
  provider: npm
  email: a.kolkov@gmail.com
  api_token: $NPM_TOKEN
  tag: latest
  edge: true
  on:
    tags: true
    repo: kolkov/ngx-gallery
